//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetInfoCollect
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOSTS_HISTORY
    {
        public int HOST_ID { get; set; }
        public Nullable<int> NODE_ID { get; set; }
        public string TYPE { get; set; }
        public string DNS_NAME { get; set; }
        public string IP { get; set; }
        public Nullable<int> TIMEOUT { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> TS_ID { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string STATUS_MESSAGE { get; set; }
        public Nullable<System.DateTime> LASTCHECKED { get; set; }
        public bool MONITOR { get; set; }
        public Nullable<System.DateTime> LASTUPDATED { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<int> MONITOR_ALERT_VALUE { get; set; }
        public Nullable<int> MONITORING_ID { get; set; }
        public int HOST_HISTORY_ID { get; set; }
    
        public virtual HOSTS HOSTS { get; set; }
    }
}
