//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetInfoCollect
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONITORING
    {
        public MONITORING()
        {
            this.HOSTS = new HashSet<HOSTS>();
            this.RESOURCES = new HashSet<RESOURCES>();
            this.RULES = new HashSet<RULES>();
            this.SERVICES = new HashSet<SERVICES>();
        }
    
        public int MONITORING_ID { get; set; }
        public bool ENABLED { get; set; }
        public Nullable<System.DateTime> LASTCHECKED { get; set; }
        public Nullable<System.DateTime> LASTUPDATED { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string STATUS_MESSAGE { get; set; }
        public Nullable<int> TIMEOUT { get; set; }
        public Nullable<int> TYPE_ID { get; set; }
        public Nullable<int> HOST_ID { get; set; }
        public Nullable<int> VALUE_INT_ALERT { get; set; }
        public Nullable<int> VALUE_INT { get; set; }
        public Nullable<int> VALUE_INT_TOTAL { get; set; }
        public string VALUE_TEXT { get; set; }
        public Nullable<int> RULE_ID { get; set; }
        public Nullable<int> SERVICE_ID { get; set; }
    
        public virtual ICollection<HOSTS> HOSTS { get; set; }
        public virtual HOSTS HOSTS1 { get; set; }
        public virtual MONITORING_TYPES MONITORING_TYPES { get; set; }
        public virtual ICollection<RESOURCES> RESOURCES { get; set; }
        public virtual ICollection<RULES> RULES { get; set; }
        public virtual ICollection<SERVICES> SERVICES { get; set; }
        public virtual RULES RULES1 { get; set; }
        public virtual SERVICES SERVICES1 { get; set; }
    }
}
