//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetInfoCollect
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONITORING_TYPES
    {
        public MONITORING_TYPES()
        {
            this.MONITORING = new HashSet<MONITORING>();
        }
    
        public int TYPE_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public int DATA_TYPE_ID { get; set; }
    
        public virtual ICollection<MONITORING> MONITORING { get; set; }
    }
}
