//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetInfoCollect
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESOURCES
    {
        public RESOURCES()
        {
            this.RESOURCES_HISTORY = new HashSet<RESOURCES_HISTORY>();
        }
    
        public int RESOURCE_ID { get; set; }
        public Nullable<int> RESOURCE_TYPE { get; set; }
        public Nullable<int> HOST_ID { get; set; }
        public Nullable<int> TOTAL { get; set; }
        public Nullable<int> FREE { get; set; }
        public string ERROR_MESSAGE { get; set; }
        public Nullable<System.DateTime> LASTCHECKED { get; set; }
        public bool MONITOR { get; set; }
        public Nullable<int> MONITOR_ALERT_VALUE { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<System.DateTime> LASTUPDATED { get; set; }
        public Nullable<int> MONITORING_ID { get; set; }
    
        public virtual HOSTS HOSTS { get; set; }
        public virtual MONITORING MONITORING { get; set; }
        public virtual ICollection<RESOURCES_HISTORY> RESOURCES_HISTORY { get; set; }
        public virtual RESOURCES_TYPES RESOURCES_TYPES { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
