//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetInfoCollect
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESOURCES_HISTORY
    {
        public int RESOURCE_ID { get; set; }
        public Nullable<int> RESOURCE_TYPE { get; set; }
        public Nullable<int> HOST_ID { get; set; }
        public Nullable<int> TOTAL { get; set; }
        public Nullable<int> FREE { get; set; }
        public string ERROR_MESSAGE { get; set; }
        public Nullable<System.DateTime> LASTCHECKED { get; set; }
        public bool MONITOR { get; set; }
        public Nullable<int> MONITOR_ALERT_VALUE { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<System.DateTime> LASTUPDATED { get; set; }
        public int RESOURCEH_ID { get; set; }
    
        public virtual RESOURCES RESOURCES { get; set; }
    }
}
