//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetInfoCollect
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESOURCES_TYPES
    {
        public RESOURCES_TYPES()
        {
            this.RESOURCES = new HashSet<RESOURCES>();
        }
    
        public int RESOURCE_TYPE_ID { get; set; }
        public string RESOURCE_NAME { get; set; }
        public string RESOURCE_DESCRIPTION { get; set; }
    
        public virtual ICollection<RESOURCES> RESOURCES { get; set; }
    }
}
