//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetInfoCollect
{
    using System;
    using System.Collections.Generic;
    
    public partial class RULES_HISTORY
    {
        public int RULE_ID { get; set; }
        public Nullable<int> FARM_ID { get; set; }
        public string RULE_NAME { get; set; }
        public string PROBE_NAME { get; set; }
        public string KEEPALIVE { get; set; }
        public Nullable<int> PORT { get; set; }
        public Nullable<int> HOST_ID { get; set; }
        public Nullable<int> S_TIMEOUT { get; set; }
        public Nullable<System.DateTime> LASTCHECKED { get; set; }
        public Nullable<int> S_STATUS { get; set; }
        public string S_STATUS_MESSAGE { get; set; }
        public string DESCRIPTION { get; set; }
        public bool MONITOR { get; set; }
        public Nullable<int> MONITOR_ALERT_VALUE { get; set; }
        public Nullable<System.DateTime> LASTUPDATED { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<int> MONITORING_ID { get; set; }
        public int RULE_HISTORY_ID { get; set; }
    
        public virtual RULES RULES { get; set; }
    }
}
