//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetInfoCollect
{
    using System;
    using System.Collections.Generic;
    
    public partial class RULES
    {
        public RULES()
        {
            this.SOCKET_STATUS = new HashSet<SOCKET_STATUS>();
            this.RULES_HISTORY = new HashSet<RULES_HISTORY>();
            this.MONITORING1 = new HashSet<MONITORING>();
        }
    
        public int RULE_ID { get; set; }
        public Nullable<int> FARM_ID { get; set; }
        public string RULE_NAME { get; set; }
        public string PROBE_NAME { get; set; }
        public string KEEPALIVE { get; set; }
        public Nullable<int> PORT { get; set; }
        public Nullable<int> HOST_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> LASTUPDATED { get; set; }
        public bool MONITOR { get; set; }
        public Nullable<int> MONITOR_ALERT_VALUE { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<int> MONITORING_ID { get; set; }
        public Nullable<int> SERVICE_ID { get; set; }
    
        public virtual HOSTS HOSTS { get; set; }
        public virtual ICollection<SOCKET_STATUS> SOCKET_STATUS { get; set; }
        public virtual FARM FARM { get; set; }
        public virtual MONITORING MONITORING { get; set; }
        public virtual ICollection<RULES_HISTORY> RULES_HISTORY { get; set; }
        public virtual ICollection<MONITORING> MONITORING1 { get; set; }
    }
}
