//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetInfoCollect
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICES
    {
        public SERVICES()
        {
            this.MONITORING1 = new HashSet<MONITORING>();
        }
    
        public int SERVICE_ID { get; set; }
        public string SERVICE_NAME { get; set; }
        public string SERVICE_DESCRIPTION { get; set; }
        public Nullable<int> MONITORING_ID { get; set; }
        public Nullable<int> HOST_ID { get; set; }
    
        public virtual HOSTS HOSTS { get; set; }
        public virtual MONITORING MONITORING { get; set; }
        public virtual ICollection<MONITORING> MONITORING1 { get; set; }
    }
}
