//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetInfoCollect
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOCKET_STATUS
    {
        public int S_STATUS_ID { get; set; }
        public Nullable<int> S_STATUS { get; set; }
        public string S_STATUS_MESSAGE { get; set; }
        public Nullable<System.DateTime> LASTUPDATED { get; set; }
        public Nullable<System.DateTime> LASTCHECKED { get; set; }
        public Nullable<int> HOST_ID { get; set; }
        public Nullable<int> S_TIMEOUT { get; set; }
        public Nullable<int> RULE_ID { get; set; }
    
        public virtual HOSTS HOSTS { get; set; }
        public virtual RULES RULES { get; set; }
    }
}
