//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetInfoCollect
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS
    {
        public TS()
        {
            this.FARM = new HashSet<FARM>();
            this.HOSTS = new HashSet<HOSTS>();
        }
    
        public int TS_ID { get; set; }
        public string TS_NAME { get; set; }
        public string TS_DESCRIPTION { get; set; }
    
        public virtual ICollection<FARM> FARM { get; set; }
        public virtual ICollection<HOSTS> HOSTS { get; set; }
    }
}
