//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetInfoCollect
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TSDBEntities : DbContext
    {
        public TSDBEntities()
            : base("name=TSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<HOSTS> HOSTS { get; set; }
        public DbSet<RULES> RULES { get; set; }
        public DbSet<FARM> FARM { get; set; }
        public DbSet<TS> TS { get; set; }
        public DbSet<SOCKET_STATUS> SOCKET_STATUS { get; set; }
        public DbSet<RESOURCES> RESOURCES { get; set; }
        public DbSet<MONITORING> MONITORING { get; set; }
        public DbSet<MONITORING_TYPES> MONITORING_TYPES { get; set; }
        public DbSet<RESOURCES_HISTORY> RESOURCES_HISTORY { get; set; }
        public DbSet<RESOURCES_TYPES> RESOURCES_TYPES { get; set; }
        public DbSet<RULES_HISTORY> RULES_HISTORY { get; set; }
        public DbSet<USERS> USERS { get; set; }
        public DbSet<SERVICES> SERVICES { get; set; }
        public DbSet<TASKS> TASKS { get; set; }
    }
}
