//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetInfoCollect
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        public USERS()
        {
            this.HOSTS = new HashSet<HOSTS>();
            this.RESOURCES = new HashSet<RESOURCES>();
        }
    
        public int USER_ID { get; set; }
        public string USERNAME { get; set; }
        public string FULLNAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> LASTUPDATED { get; set; }
    
        public virtual ICollection<HOSTS> HOSTS { get; set; }
        public virtual ICollection<RESOURCES> RESOURCES { get; set; }
    }
}
